#=========================================
#================= server config
#=========================================
server:
  port: 8180
  context-path: /es
  tomcat:
    uri-encoding: UTF-8
#=========================================
#================= server log
#=========================================
logging:
  level:
    root: info
    com.qbian: debug
#=========================================
#================= spring config
#=========================================
spring:
  profiles:
    active: es
  thymeleaf:
    cache: false
